SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `telebase_v6_dev`.`cache`;
INSERT INTO `telebase_v6_dev`.`cache` (`key`,`value`,`expiration`) SELECT `key`,`value`,`expiration` FROM `telebase_v6_raw`.`cache`;
TRUNCATE TABLE `telebase_v6_dev`.`cache_locks`;
INSERT INTO `telebase_v6_dev`.`cache_locks` (`key`,`owner`,`expiration`) SELECT `key`,`owner`,`expiration` FROM `telebase_v6_raw`.`cache_locks`;
TRUNCATE TABLE `telebase_v6_dev`.`cnt_contents`;
INSERT INTO `telebase_v6_dev`.`cnt_contents` (`id`,`user_id`,`source_module`,`source_id`,`field`,`kind`,`title`,`body_md`,`body_hash`,`locale`,`status`,`is_primary`,`sort_order`,`meta`,`created_at`,`updated_at`,`deleted_at`) SELECT `id`,`user_id`,`source_module`,`source_id`,`field`,`kind`,`title`,`body_md`,`body_hash`,`locale`,`status`,`is_primary`,`sort_order`,`meta`,`created_at`,`updated_at`,`deleted_at` FROM `telebase_v6_raw`.`cnt_contents`;
TRUNCATE TABLE `telebase_v6_dev`.`evt_categories`;
INSERT INTO `telebase_v6_dev`.`evt_categories` (`id`,`user_id`,`name`,`description`,`color`,`bgcolor`,`sort_order`,`is_archived`,`is_default`,`created_at`,`updated_at`) SELECT `id`,`user_id`,`name`,`description`,`color`,`bgcolor`,`sort_order`,`is_archived`,`is_default`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`evt_categories`;
TRUNCATE TABLE `telebase_v6_dev`.`evt_embeds`;
INSERT INTO `telebase_v6_dev`.`evt_embeds` (`id`,`event_id`,`user_id`,`url`,`provider`,`type`,`title`,`author`,`thumbnail_url`,`duration`,`meta`,`order`,`created_at`,`updated_at`) SELECT `id`,`event_id`,`user_id`,`url`,`provider`,`type`,`title`,`author`,`thumbnail_url`,`duration`,`meta`,`order`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`evt_embeds`;
TRUNCATE TABLE `telebase_v6_dev`.`evt_events`;
INSERT INTO `telebase_v6_dev`.`evt_events` (`id`,`name`,`user_id`,`type_id`,`format`,`metadata`,`language`,`code_language`,`section_id`,`category_id`,`project_id`,`exploiter_event_id`,`location`,`client`,`content`,`status`,`sort_order`,`access`,`comment_access`,`parent_id`,`root_id`,`relation_type`,`is_blurred`,`is_locked`,`is_pinned`,`occurred_at`,`created_at`,`updated_at`) SELECT `id`,`name`,`user_id`,`type_id`,`format`,`metadata`,`language`,`code_language`,`section_id`,`category_id`,`project_id`,`exploiter_event_id`,`location`,`client`,`content`,`status`,`sort_order`,`access`,`comment_access`,`parent_id`,`root_id`,`relation_type`,`is_blurred`,`is_locked`,`is_pinned`,`occurred_at`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`evt_events`;
TRUNCATE TABLE `telebase_v6_dev`.`evt_event_tags`;
INSERT INTO `telebase_v6_dev`.`evt_event_tags` (`event_id`,`tag_id`) SELECT `event_id`,`tag_id` FROM `telebase_v6_raw`.`evt_event_tags`;
TRUNCATE TABLE `telebase_v6_dev`.`evt_media`;
INSERT INTO `telebase_v6_dev`.`evt_media` (`id`,`event_id`,`user_id`,`url`,`path`,`mime_type`,`size`,`width`,`height`,`sort_order`,`meta`,`created_at`,`updated_at`) SELECT `id`,`event_id`,`user_id`,`url`,`path`,`mime_type`,`size`,`width`,`height`,`sort_order`,`meta`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`evt_media`;
TRUNCATE TABLE `telebase_v6_dev`.`evt_sections`;
INSERT INTO `telebase_v6_dev`.`evt_sections` (`id`,`user_id`,`name`,`literals`,`description`,`sort_order`,`access`,`color`,`bgcolor`,`icon`,`decor`,`seo`,`is_archived`,`is_default`,`created_at`,`updated_at`) SELECT `id`,`user_id`,`name`,`literals`,`description`,`sort_order`,`access`,`color`,`bgcolor`,`icon`,`decor`,`seo`,`is_archived`,`is_default`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`evt_sections`;
TRUNCATE TABLE `telebase_v6_dev`.`evt_starred`;
INSERT INTO `telebase_v6_dev`.`evt_starred` (`user_id`,`event_id`,`created_at`,`updated_at`) SELECT `user_id`,`event_id`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`evt_starred`;
TRUNCATE TABLE `telebase_v6_dev`.`evt_tags`;
INSERT INTO `telebase_v6_dev`.`evt_tags` (`id`,`user_id`,`name`,`slug`,`color`,`bgcolor`,`is_system`,`sort_order`,`is_archived`,`created_at`,`updated_at`) SELECT `id`,`user_id`,`name`,`slug`,`color`,`bgcolor`,`is_system`,`sort_order`,`is_archived`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`evt_tags`;
TRUNCATE TABLE `telebase_v6_dev`.`evt_types`;
INSERT INTO `telebase_v6_dev`.`evt_types` (`id`,`user_id`,`name`,`description`,`color`,`bgcolor`,`sort_order`,`icon`,`is_archived`,`is_default`,`created_at`,`updated_at`) SELECT `id`,`user_id`,`name`,`description`,`color`,`bgcolor`,`sort_order`,`icon`,`is_archived`,`is_default`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`evt_types`;
TRUNCATE TABLE `telebase_v6_dev`.`failed_jobs`;
INSERT INTO `telebase_v6_dev`.`failed_jobs` (`id`,`uuid`,`connection`,`queue`,`payload`,`exception`,`failed_at`) SELECT `id`,`uuid`,`connection`,`queue`,`payload`,`exception`,`failed_at` FROM `telebase_v6_raw`.`failed_jobs`;
TRUNCATE TABLE `telebase_v6_dev`.`jobs`;
INSERT INTO `telebase_v6_dev`.`jobs` (`id`,`queue`,`payload`,`attempts`,`reserved_at`,`available_at`,`created_at`) SELECT `id`,`queue`,`payload`,`attempts`,`reserved_at`,`available_at`,`created_at` FROM `telebase_v6_raw`.`jobs`;
TRUNCATE TABLE `telebase_v6_dev`.`job_batches`;
INSERT INTO `telebase_v6_dev`.`job_batches` (`id`,`name`,`total_jobs`,`pending_jobs`,`failed_jobs`,`failed_job_ids`,`options`,`cancelled_at`,`created_at`,`finished_at`) SELECT `id`,`name`,`total_jobs`,`pending_jobs`,`failed_jobs`,`failed_job_ids`,`options`,`cancelled_at`,`created_at`,`finished_at` FROM `telebase_v6_raw`.`job_batches`;
TRUNCATE TABLE `telebase_v6_dev`.`led_accounts`;
INSERT INTO `telebase_v6_dev`.`led_accounts` (`id`,`user_id`,`layer_id`,`name`,`literals`,`type`,`currency`,`opening_balance`,`color`,`sort_order`,`opened_at`,`closed_at`,`interest_rate`,`interest_start`,`is_archived`,`created_at`,`updated_at`) SELECT `id`,`user_id`,`layer_id`,`name`,`literals`,`type`,`currency`,`opening_balance`,`color`,`sort_order`,`opened_at`,`closed_at`,`interest_rate`,`interest_start`,`is_archived`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`led_accounts`;
TRUNCATE TABLE `telebase_v6_dev`.`led_categories`;
INSERT INTO `telebase_v6_dev`.`led_categories` (`id`,`user_id`,`parent_id`,`name`,`depth`,`path`,`sort_order`,`is_archived`,`created_at`,`updated_at`) SELECT `id`,`user_id`,`parent_id`,`name`,`depth`,`path`,`sort_order`,`is_archived`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`led_categories`;
TRUNCATE TABLE `telebase_v6_dev`.`led_layers`;
INSERT INTO `telebase_v6_dev`.`led_layers` (`id`,`user_id`,`name`,`type`,`parent_id`,`is_active`,`created_at`,`updated_at`) SELECT `id`,`user_id`,`name`,`type`,`parent_id`,`is_active`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`led_layers`;
TRUNCATE TABLE `telebase_v6_dev`.`led_month_totals`;
INSERT INTO `telebase_v6_dev`.`led_month_totals` (`id`,`user_id`,`layer_id`,`account_id`,`month_key`,`opening_balance`,`closing_balance`,`income_total`,`expense_total`,`transfer_in_total`,`transfer_out_total`,`adjustment_total`,`interest_total`,`tx_count`,`is_dirty`,`created_at`,`updated_at`) SELECT `id`,`user_id`,`layer_id`,`account_id`,`month_key`,`opening_balance`,`closing_balance`,`income_total`,`expense_total`,`transfer_in_total`,`transfer_out_total`,`adjustment_total`,`interest_total`,`tx_count`,`is_dirty`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`led_month_totals`;
TRUNCATE TABLE `telebase_v6_dev`.`led_transactions`;
INSERT INTO `telebase_v6_dev`.`led_transactions` (`id`,`user_id`,`layer_id`,`account_id`,`target_account_id`,`group_id`,`category_id`,`original_transaction_id`,`flow_kind`,`amount`,`is_negative`,`occurred_at`,`month_key`,`title`,`note`,`status`,`is_disabled`,`is_pinned`,`sort_order`,`exploiter_event_id`,`cost_type`,`linked_entity_type`,`linked_entity_id`,`created_at`,`updated_at`,`deleted_at`) SELECT `id`,`user_id`,`layer_id`,`account_id`,`target_account_id`,`group_id`,`category_id`,`original_transaction_id`,`flow_kind`,`amount`,`is_negative`,`occurred_at`,`month_key`,`title`,`note`,`status`,`is_disabled`,`is_pinned`,`sort_order`,`exploiter_event_id`,`cost_type`,`linked_entity_type`,`linked_entity_id`,`created_at`,`updated_at`,`deleted_at` FROM `telebase_v6_raw`.`led_transactions`;
TRUNCATE TABLE `telebase_v6_dev`.`led_transaction_groups`;
INSERT INTO `telebase_v6_dev`.`led_transaction_groups` (`id`,`user_id`,`name`,`is_disabled`,`color`,`created_at`,`updated_at`) SELECT `id`,`user_id`,`name`,`is_disabled`,`color`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`led_transaction_groups`;
TRUNCATE TABLE `telebase_v6_dev`.`led_transaction_tags`;
INSERT INTO `telebase_v6_dev`.`led_transaction_tags` (`transaction_id`,`tag_id`) SELECT `transaction_id`,`tag_id` FROM `telebase_v6_raw`.`led_transaction_tags`;
TRUNCATE TABLE `telebase_v6_dev`.`password_reset_tokens`;
INSERT INTO `telebase_v6_dev`.`password_reset_tokens` (`email`,`token`,`created_at`) SELECT `email`,`token`,`created_at` FROM `telebase_v6_raw`.`password_reset_tokens`;
TRUNCATE TABLE `telebase_v6_dev`.`refresh_tokens`;
INSERT INTO `telebase_v6_dev`.`refresh_tokens` (`id`,`token`,`user_id`,`user_agent`,`ip_address`,`expires_at`,`created_at`,`updated_at`) SELECT `id`,`token`,`user_id`,`user_agent`,`ip_address`,`expires_at`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`refresh_tokens`;
TRUNCATE TABLE `telebase_v6_dev`.`sessions`;
INSERT INTO `telebase_v6_dev`.`sessions` (`id`,`user_id`,`ip_address`,`user_agent`,`payload`,`last_activity`) SELECT `id`,`user_id`,`ip_address`,`user_agent`,`payload`,`last_activity` FROM `telebase_v6_raw`.`sessions`;
TRUNCATE TABLE `telebase_v6_dev`.`stf_expenses`;
INSERT INTO `telebase_v6_dev`.`stf_expenses` (`id`,`user_id`,`thing_id`,`register_id`,`transaction_id`,`amount`,`note`,`occurred_at`,`created_at`,`updated_at`) SELECT `id`,`user_id`,`thing_id`,`register_id`,`transaction_id`,`amount`,`note`,`occurred_at`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`stf_expenses`;
TRUNCATE TABLE `telebase_v6_dev`.`stf_locations`;
INSERT INTO `telebase_v6_dev`.`stf_locations` (`id`,`user_id`,`name`,`parent_id`,`sort_order`,`is_archived`,`created_at`,`updated_at`,`deleted_at`) SELECT `id`,`user_id`,`name`,`parent_id`,`sort_order`,`is_archived`,`created_at`,`updated_at`,`deleted_at` FROM `telebase_v6_raw`.`stf_locations`;
TRUNCATE TABLE `telebase_v6_dev`.`stf_register`;
INSERT INTO `telebase_v6_dev`.`stf_register` (`id`,`user_id`,`thing_id`,`event_type`,`event_kind`,`from_location_id`,`to_location_id`,`contact`,`return_expected`,`amount`,`note`,`details`,`status`,`priority`,`is_pinned`,`part_cost`,`labor_cost`,`time_self_min`,`time_service_min`,`occurred_at`,`created_at`,`updated_at`) SELECT `id`,`user_id`,`thing_id`,`event_type`,`event_kind`,`from_location_id`,`to_location_id`,`contact`,`return_expected`,`amount`,`note`,`details`,`status`,`priority`,`is_pinned`,`part_cost`,`labor_cost`,`time_self_min`,`time_service_min`,`occurred_at`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`stf_register`;
TRUNCATE TABLE `telebase_v6_dev`.`stf_things`;
INSERT INTO `telebase_v6_dev`.`stf_things` (`id`,`user_id`,`entity_type`,`name`,`description`,`vendor`,`url`,`parent_id`,`category_id`,`current_location_id`,`current_status`,`serial_no`,`qty`,`unit`,`purchase_price`,`purchase_date`,`open_count`,`last_opened_at`,`is_archived`,`track_location`,`track_lifecycle`,`created_at`,`updated_at`,`deleted_at`) SELECT `id`,`user_id`,`entity_type`,`name`,`description`,`vendor`,`url`,`parent_id`,`category_id`,`current_location_id`,`current_status`,`serial_no`,`qty`,`unit`,`purchase_price`,`purchase_date`,`open_count`,`last_opened_at`,`is_archived`,`track_location`,`track_lifecycle`,`created_at`,`updated_at`,`deleted_at` FROM `telebase_v6_raw`.`stf_things`;
TRUNCATE TABLE `telebase_v6_dev`.`sys_templates`;
INSERT INTO `telebase_v6_dev`.`sys_templates` (`id`,`user_id`,`module`,`name`,`icon`,`payload`,`schedule`,`status`,`sort_order`,`created_at`,`updated_at`,`deleted_at`) SELECT `id`,`user_id`,`module`,`name`,`icon`,`payload`,`schedule`,`status`,`sort_order`,`created_at`,`updated_at`,`deleted_at` FROM `telebase_v6_raw`.`sys_templates`;
TRUNCATE TABLE `telebase_v6_dev`.`sys_timer_entries`;
INSERT INTO `telebase_v6_dev`.`sys_timer_entries` (`id`,`user_id`,`started_at`,`ended_at`,`duration_min`,`entry_type`,`time_type`,`source_module`,`source_id`,`sort_order`,`note`,`created_at`,`updated_at`,`deleted_at`) SELECT `id`,`user_id`,`started_at`,`ended_at`,`duration_min`,`entry_type`,`time_type`,`source_module`,`source_id`,`sort_order`,`note`,`created_at`,`updated_at`,`deleted_at` FROM `telebase_v6_raw`.`sys_timer_entries`;
TRUNCATE TABLE `telebase_v6_dev`.`users`;
INSERT INTO `telebase_v6_dev`.`users` (`id`,`name`,`email`,`email_verified_at`,`password`,`status`,`is_demo`,`demo_seeded_at`,`remember_token`,`current_team_id`,`profile_photo_path`,`created_at`,`updated_at`) SELECT `id`,`name`,`email`,`email_verified_at`,`password`,`status`,`is_demo`,`demo_seeded_at`,`remember_token`,`current_team_id`,`profile_photo_path`,`created_at`,`updated_at` FROM `telebase_v6_raw`.`users`;
SET FOREIGN_KEY_CHECKS=1;
