export const CONTACT_GROUPS = [
  { value: 'all', label: 'All groups' },
  { value: 'family', label: 'Family' },
  { value: 'friends', label: 'Friends' },
  { value: 'work', label: 'Work' },
  { value: 'service', label: 'Service' },
  { value: 'acquaintance', label: 'Acquaintance' },
];

export const LOG_KINDS = [
  { value: 'fact', label: 'Fact' },
  { value: 'meeting', label: 'Meeting' },
  { value: 'call', label: 'Call' },
  { value: 'note', label: 'Note' },
  { value: 'reminder_done', label: 'Reminder done' },
];

export const RELATION_KINDS = [
  { value: 'classmate', label: 'Classmate' },
  { value: 'groupmate', label: 'Groupmate' },
  { value: 'colleague', label: 'Colleague' },
  { value: 'friend', label: 'Friend' },
  { value: 'family', label: 'Family' },
  { value: 'neighbor', label: 'Neighbor' },
  { value: 'other', label: 'Other' },
];

export const MOCK_CONTACTS = [
  {
    id: 'cnt-1',
    name: 'Alex Morgan',
    nickname: 'Alex',
    group: 'work',
    role: 'Product lead',
    company: 'Northline Labs',
    avatar: '',
    met_at: '2022-03-15',
    met_context: 'Product meetup SF',
    last_contact_at: '2026-07-12T15:20:00',
    is_archived: false,
    details: [
      { kind: 'phone', label: 'Mobile', value: '+1 415 555 0182', sort_order: 1 },
      { kind: 'tg', label: 'Telegram', value: '@alexmorgan', sort_order: 2 },
      { kind: 'email', label: 'Work', value: 'alex@northline.example', sort_order: 3 },
      { kind: 'address', label: 'City', value: 'San Francisco, CA', sort_order: 4 },
    ],
  },
  {
    id: 'cnt-2',
    name: 'Maya Chen',
    nickname: '',
    group: 'friends',
    role: 'Designer',
    company: 'Freelance',
    avatar: '',
    met_at: '2015-09-01',
    met_context: 'Design school',
    last_contact_at: '2026-07-02T11:00:00',
    is_archived: false,
    details: [
      { kind: 'phone', label: 'Mobile', value: '+1 646 555 0144', sort_order: 1 },
      { kind: 'tg', label: 'Telegram', value: '@mayasketch', sort_order: 2 },
      { kind: 'email', label: 'Personal', value: 'maya@example.com', sort_order: 3 },
      { kind: 'address', label: 'City', value: 'Brooklyn, NY', sort_order: 4 },
    ],
  },
  {
    id: 'cnt-3',
    name: 'Daniel Foster',
    nickname: 'Diesel Dan',
    group: 'service',
    role: 'Auto mechanic',
    company: 'Foster Garage',
    avatar: '',
    met_at: '2023-06-10',
    met_context: 'Recommended by Nikolai',
    last_contact_at: '2026-06-18T09:30:00',
    is_archived: false,
    details: [
      { kind: 'phone', label: 'Work', value: '+1 312 555 0199', sort_order: 1 },
      { kind: 'email', label: 'Work', value: 'service@fostergarage.example', sort_order: 2 },
      { kind: 'address', label: 'Garage', value: 'Chicago, IL', sort_order: 3 },
    ],
  },
  {
    id: 'cnt-4',
    name: 'Sofia Rivera',
    nickname: 'Sofie',
    group: 'family',
    role: 'Sister',
    company: '',
    avatar: '',
    met_at: null,
    met_context: '',
    last_contact_at: '2026-07-14T20:15:00',
    is_archived: false,
    details: [
      { kind: 'phone', label: 'Mobile', value: '+1 213 555 0102', sort_order: 1 },
      { kind: 'tg', label: 'Telegram', value: '@sofiar', sort_order: 2 },
      { kind: 'email', label: 'Personal', value: 'sofia@example.com', sort_order: 3 },
      { kind: 'address', label: 'City', value: 'Los Angeles, CA', sort_order: 4 },
    ],
  },
  {
    id: 'cnt-5',
    name: 'Nikolai Petrov',
    nickname: 'Nik',
    group: 'work',
    role: 'Backend engineer',
    company: 'Teftele',
    avatar: '',
    met_at: '2026-01-01',
    met_context: 'Teftele team',
    last_contact_at: '2026-06-30T17:45:00',
    is_archived: false,
    details: [
      { kind: 'tg', label: 'Telegram', value: '@nikpetrov', sort_order: 1 },
      { kind: 'email', label: 'Work', value: 'nikolai@teftele.example', sort_order: 2 },
    ],
  },
  {
    id: 'cnt-6',
    name: 'Emma Wilson',
    nickname: '',
    group: 'acquaintance',
    role: 'University friend',
    company: '',
    avatar: '',
    met_at: '2019-09-01',
    met_context: 'University exchange programme',
    last_contact_at: '2026-05-21T14:10:00',
    is_archived: false,
    details: [
      { kind: 'phone', label: 'Mobile', value: '+44 20 7946 0244', sort_order: 1 },
      { kind: 'tg', label: 'Telegram', value: '@emwilson', sort_order: 2 },
      { kind: 'email', label: 'Personal', value: 'emma@example.co.uk', sort_order: 3 },
      { kind: 'address', label: 'City', value: 'London, UK', sort_order: 4 },
    ],
  },
];

export const MOCK_LOGS = [
  {
    id: 'log-1',
    contact_id: 'cnt-1',
    kind: 'meeting',
    occurred_at: '2026-07-12T15:20:00',
    title: 'Roadmap sync',
    content: 'Discussed the contact graph, import flow, and demo data strategy.',
    eventor_event_id: 'evt-120',
    stuffer_register_id: null,
    exploiter_event_id: null,
    is_pinned: false,
  },
  {
    id: 'log-2',
    contact_id: 'cnt-4',
    kind: 'call',
    occurred_at: '2026-07-14T20:15:00',
    title: 'Family call',
    content: 'Quick call before the weekend.',
    eventor_event_id: null,
    stuffer_register_id: null,
    exploiter_event_id: null,
    is_pinned: false,
  },
  {
    id: 'log-3',
    contact_id: 'cnt-2',
    kind: 'note',
    occurred_at: '2026-07-02T11:00:00',
    title: 'Portfolio links',
    content: 'Sent links to the new portfolio. Review before Friday.',
    eventor_event_id: null,
    stuffer_register_id: null,
    exploiter_event_id: null,
    is_pinned: true,
  },
  {
    id: 'log-4',
    contact_id: 'cnt-5',
    kind: 'meeting',
    occurred_at: '2026-06-30T17:45:00',
    title: 'Backend migration call',
    content: 'Agreed on namespacing and SQL export strategy.',
    eventor_event_id: 'evt-104',
    stuffer_register_id: null,
    exploiter_event_id: null,
    is_pinned: false,
  },
  {
    id: 'log-5',
    contact_id: 'cnt-3',
    kind: 'fact',
    occurred_at: '2026-06-18T09:30:00',
    title: 'BMW service contact',
    content: 'Recommended for diesel diagnostics and suspension work.',
    eventor_event_id: null,
    stuffer_register_id: null,
    exploiter_event_id: 'exp-21',
    is_pinned: true,
  },
  {
    id: 'log-6',
    contact_id: 'cnt-6',
    kind: 'call',
    occurred_at: '2026-05-21T14:10:00',
    title: 'London trip advice',
    content: 'Shared quiet cafe recommendations near Shoreditch.',
    eventor_event_id: null,
    stuffer_register_id: null,
    exploiter_event_id: null,
    is_pinned: false,
  },
];

export const MOCK_RELATIONS = [
  {
    id: 'rel-1',
    contact_a_id: 'cnt-1',
    contact_b_id: 'cnt-5',
    kind: 'colleague',
    context: 'Teftele 2026',
    valid_from: '2026-01-01',
    valid_to: null,
    note: '',
  },
  {
    id: 'rel-2',
    contact_a_id: 'cnt-2',
    contact_b_id: 'cnt-6',
    kind: 'classmate',
    context: 'Design school 2015',
    valid_from: '2015-09-01',
    valid_to: null,
    note: '',
  },
  {
    id: 'rel-3',
    contact_a_id: 'cnt-1',
    contact_b_id: 'cnt-2',
    kind: 'friend',
    context: 'Product meetup SF 2024',
    valid_from: '2024-04-12',
    valid_to: null,
    note: '',
  },
  {
    id: 'rel-4',
    contact_a_id: 'cnt-4',
    contact_b_id: 'cnt-6',
    kind: 'friend',
    context: 'Travel group',
    valid_from: '2023-08-20',
    valid_to: '2025-12-31',
    note: 'Lost touch after relocation.',
  },
];
