export const FACT_KINDS = [
  { value: 'all', label: 'All' },
  { value: 'document', label: 'Document' },
  { value: 'technical', label: 'Technical' },
  { value: 'professional', label: 'Professional' },
  { value: 'personal', label: 'Personal' },
  { value: 'other', label: 'Other' },
];

export const FACT_FORMATS = [
  { value: 'text', label: 'Text' },
  { value: 'markdown', label: 'Markdown' },
  { value: 'code', label: 'Code' },
  { value: 'command', label: 'Command' },
  { value: 'number', label: 'Number' },
  { value: 'svg', label: 'SVG' },
];

export const FACT_DISPLAY_MODES = [
  { value: 'plain', label: 'Plain' },
  { value: 'large', label: 'Large' },
  { value: 'mono', label: 'Mono' },
  { value: 'article', label: 'Article' },
  { value: 'snippet', label: 'Snippet' },
  { value: 'terminal', label: 'Terminal' },
  { value: 'metric', label: 'Metric' },
  { value: 'preview', label: 'Preview' },
  { value: 'qr', label: 'QR' },
  { value: 'masked', label: 'Masked' },
];

export const factMocks = [
  {
    id: 'fact-vin-bmw-e90',
    label: 'VIN BMW E90',
    value: 'WBA3G510X0NS47291',
    format: 'text',
    language: null,
    unit: null,
    context: 'From purchase listing, July 2024',
    search_keywords: ['bmw vin', 'car vin', 'e90 body number', 'bmw', 'car', 'vin'],
    kind: 'document',
    display_mode: 'large',
    is_sensitive: false,
    is_expert: false,
    valid_from: null,
    valid_to: null,
    is_pinned: true,
    sort_order: 10,
    created_at: '2026-07-18 10:00:00',
    updated_at: '2026-07-18 10:00:00',
  },
  {
    id: 'fact-oil-bmw-e90',
    label: 'BMW E90 engine oil',
    value: '5W-40 LL-04',
    format: 'text',
    language: null,
    unit: null,
    context: 'Preferred oil spec for current service plan',
    search_keywords: ['oil spec', 'engine oil', 'bmw service fluid', 'bmw', 'service', 'oil'],
    kind: 'technical',
    display_mode: 'large',
    is_sensitive: false,
    is_expert: false,
    valid_from: '2024-07-01',
    valid_to: null,
    is_pinned: true,
    sort_order: 20,
    created_at: '2026-07-18 10:10:00',
    updated_at: '2026-07-18 10:10:00',
  },
  {
    id: 'fact-filter-mann',
    label: 'MANN oil filter part number',
    value: 'HU 816 x',
    format: 'text',
    language: null,
    unit: null,
    context: 'Checked against BMW service records',
    search_keywords: ['oil filter', 'mann filter', 'bmw part', 'bmw', 'part', 'filter'],
    kind: 'technical',
    display_mode: 'large',
    is_sensitive: false,
    is_expert: false,
    valid_from: null,
    valid_to: null,
    is_pinned: false,
    sort_order: 30,
    created_at: '2026-07-18 10:20:00',
    updated_at: '2026-07-18 10:20:00',
  },
  {
    id: 'fact-rental-contract',
    label: 'Apartment rental contract',
    value: 'AGR-2025-11-044',
    format: 'text',
    language: null,
    unit: null,
    context: 'Used for payment references',
    search_keywords: ['rent agreement', 'contract number', 'apartment', 'contract'],
    kind: 'document',
    display_mode: 'mono',
    is_sensitive: true,
    is_expert: false,
    valid_from: '2025-11-01',
    valid_to: null,
    is_pinned: false,
    sort_order: 40,
    created_at: '2026-07-18 10:30:00',
    updated_at: '2026-07-18 10:30:00',
  },
  {
    id: 'fact-conference-architect',
    label: 'Architect from conference',
    value: 'Alex Martin, Northwind Systems',
    format: 'text',
    language: null,
    unit: null,
    context: 'Met at backend architecture meetup',
    search_keywords: ['backend meetup', 'northwind', 'people', 'architecture'],
    kind: 'professional',
    display_mode: 'plain',
    is_sensitive: false,
    is_expert: false,
    valid_from: null,
    valid_to: null,
    is_pinned: false,
    sort_order: 50,
    created_at: '2026-07-18 10:40:00',
    updated_at: '2026-07-18 10:40:00',
  },
  {
    id: 'fact-old-office-address',
    label: 'Old office address',
    value: '18 Market Street, floor 4',
    format: 'text',
    language: null,
    unit: null,
    context: 'Legacy address, keep only for old documents',
    search_keywords: ['legacy address', 'office', 'address', 'archive'],
    kind: 'personal',
    display_mode: 'qr',
    is_sensitive: false,
    is_expert: false,
    valid_from: '2022-01-01',
    valid_to: '2025-12-31',
    is_pinned: false,
    sort_order: 60,
    created_at: '2026-07-18 10:50:00',
    updated_at: '2026-07-18 10:50:00',
  },
  {
    id: 'fact-docker-backend',
    label: 'Backend docker restart',
    value: 'docker compose restart php nginx',
    format: 'command',
    language: 'bash',
    unit: null,
    context: 'Local stack maintenance command',
    search_keywords: ['docker restart', 'backend restart', 'nginx php', 'docker', 'local'],
    kind: 'technical',
    display_mode: 'terminal',
    is_sensitive: false,
    is_expert: true,
    valid_from: null,
    valid_to: null,
    is_pinned: false,
    sort_order: 70,
    created_at: '2026-07-18 11:00:00',
    updated_at: '2026-07-18 11:00:00',
  },
  {
    id: 'fact-storage-usage',
    label: 'Home storage capacity',
    value: '8.4',
    format: 'number',
    language: null,
    unit: 'TB',
    context: 'Usable storage after parity',
    search_keywords: ['nas capacity', 'storage'],
    kind: 'technical',
    display_mode: 'metric',
    is_sensitive: false,
    is_expert: false,
    valid_from: null,
    valid_to: null,
    is_pinned: false,
    sort_order: 80,
    created_at: '2026-07-18 11:10:00',
    updated_at: '2026-07-18 11:10:00',
  },
];
