// ── Локации (дерево) ──────────────────────────────────────────────
export const MOCK_LOCATIONS = [
  { id: 'loc-1', name: 'Квартира', parent_id: null, sort_order: 1 },
  { id: 'loc-2', name: 'Старая квартира', parent_id: null, sort_order: 2 },
  { id: 'loc-3', name: 'Машина', parent_id: null, sort_order: 3 },
  { id: 'loc-4', name: 'Гараж', parent_id: null, sort_order: 4 },
  { id: 'loc-1-1', name: 'Кладовка', parent_id: 'loc-1', sort_order: 1 },
  { id: 'loc-1-2', name: 'Рабочий стол', parent_id: 'loc-1', sort_order: 2 },
  { id: 'loc-1-3', name: 'Шкаф в прихожей', parent_id: 'loc-1', sort_order: 3 },
  { id: 'loc-3-1', name: 'Багажник', parent_id: 'loc-3', sort_order: 1 },
  { id: 'loc-3-2', name: 'Бардачок', parent_id: 'loc-3', sort_order: 2 },
];

// ── Категории ─────────────────────────────────────────────────────
export const MOCK_CATEGORIES = [
  { id: 'cat-1', name: 'Электроника', color: '#3b82f6' },
  { id: 'cat-2', name: 'Инструменты', color: '#f59e0b' },
  { id: 'cat-3', name: 'Авто', color: '#ef4444' },
  { id: 'cat-4', name: 'Фото/Видео', color: '#8b5cf6' },
  { id: 'cat-5', name: 'Одежда', color: '#06b6d4' },
];

// ── Вещи (Asset + Item в одной таблице) ──────────────────────────
export const MOCK_THINGS = [
  {
    id: 'thing-1',
    entity_type: 'asset',
    name: 'BMW 320d',
    description: 'Основная машина. Чёрный, 2018 г.',
    category_id: 'cat-3',
    current_location_id: null, // машина сама — локация
    current_status: 'active',
    serial_no: 'WBA8E3100K1234567',
    purchase_price: 220000000, // копейки
    purchase_date: '2021-03-15',
    parent_id: null,
    open_count: 42,
    last_opened_at: '2026-04-23T10:00:00',
    is_archived: false,
    url: null,
    vendor: null,
  },
  {
    id: 'thing-2',
    entity_type: 'asset',
    name: 'Ноутбук Lenovo X1 Carbon',
    description: 'Gen 10, 32GB, 1TB SSD. Рабочий.',
    category_id: 'cat-1',
    current_location_id: 'loc-1-2',
    current_status: 'active',
    serial_no: 'MP2CXXXXX',
    purchase_price: 17500000,
    purchase_date: '2023-09-01',
    parent_id: null,
    open_count: 31,
    last_opened_at: '2026-04-22T18:30:00',
    is_archived: false,
    url: null,
    vendor: 'Lenovo',
  },
  {
    id: 'thing-3',
    entity_type: 'asset',
    name: 'Домашний сервер',
    description: 'Proxmox, 64GB RAM, 4x8TB HDD',
    category_id: 'cat-1',
    current_location_id: 'loc-1-1',
    current_status: 'active',
    serial_no: null,
    purchase_price: 8500000,
    purchase_date: '2022-06-10',
    parent_id: null,
    open_count: 18,
    last_opened_at: '2026-04-20T09:00:00',
    is_archived: false,
    url: null,
    vendor: null,
  },
  {
    id: 'thing-4',
    entity_type: 'asset',
    name: 'Фоторюкзак Peak Design 45L',
    description: 'Серый. Основной рюкзак для выездов.',
    category_id: 'cat-4',
    current_location_id: 'loc-1',
    current_status: 'active',
    serial_no: null,
    purchase_price: 4200000,
    purchase_date: '2020-11-20',
    parent_id: null,
    open_count: 27,
    last_opened_at: '2026-04-18T14:00:00',
    is_archived: false,
    url: null,
    vendor: 'Peak Design',
  },
  {
    id: 'thing-5',
    entity_type: 'item',
    name: 'Масляный фильтр Mann W712/75',
    description: 'Для BMW N47. 3 штуки.',
    category_id: 'cat-3',
    current_location_id: 'loc-3-1', // в багажнике... или в рюкзаке?
    current_status: 'stored',
    serial_no: null,
    purchase_price: 230000, // 2300 руб за 3 шт
    purchase_date: '2026-04-10',
    parent_id: 'thing-1', // относится к BMW
    qty: 3,
    unit: 'шт',
    open_count: 5,
    last_opened_at: '2026-04-23T11:00:00',
    is_archived: false,
    url: 'https://ozon.ru/product/xxx',
    vendor: 'Авто-маг',
  },
  {
    id: 'thing-6',
    entity_type: 'item',
    name: 'Паяльник для пластика Forsthoff',
    description: 'Профессиональный, 600Вт. Для ремонта бамперов.',
    category_id: 'cat-2',
    current_location_id: null, // ещё не приехал
    current_status: 'ordered',
    serial_no: null,
    purchase_price: 230000,
    purchase_date: '2026-04-22',
    parent_id: null,
    qty: 1,
    unit: 'шт',
    open_count: 3,
    last_opened_at: '2026-04-23T09:00:00',
    is_archived: false,
    url: 'https://ozon.ru/product/forsthoff-600w',
    vendor: 'ИП Сидоров / Ozon',
  },
  {
    id: 'thing-7',
    entity_type: 'item',
    name: 'SSD Samsung 870 EVO 4TB',
    description: 'В сервер, 4й слот',
    category_id: 'cat-1',
    current_location_id: 'loc-1-1',
    current_status: 'installed',
    serial_no: 'S5GXNF0T123456',
    purchase_price: 1890000,
    purchase_date: '2024-02-15',
    parent_id: 'thing-3', // относится к серверу
    qty: 1,
    unit: 'шт',
    open_count: 8,
    last_opened_at: '2026-03-10T10:00:00',
    is_archived: false,
    url: null,
    vendor: 'DNS',
  },
  {
    id: 'thing-8',
    entity_type: 'item',
    name: 'Дрель Bosch GSB 18V',
    description: 'Дал Шурику до выходных',
    category_id: 'cat-2',
    current_location_id: null,
    current_status: 'lent',
    serial_no: null,
    purchase_price: 890000,
    purchase_date: '2022-03-01',
    parent_id: null,
    qty: 1,
    unit: 'шт',
    open_count: 12,
    last_opened_at: '2026-04-21T15:00:00',
    is_archived: false,
    url: null,
    vendor: 'Bosch',
    lent_to: 'Шурик',
    lent_at: '2026-04-20',
  },
];

// ── Регистры (события) ────────────────────────────────────────────
export const MOCK_REGISTER = [
  {
    id: 'reg-1',
    thing_id: 'thing-6',
    event_type: 'ordered',
    from_location_id: null,
    to_location_id: null,
    note: 'Заказал на Ozon. ИП Сидоров, 2300₽. Ожидается 25 апреля.',
    occurred_at: '2026-04-22',
  },
  {
    id: 'reg-2',
    thing_id: 'thing-5',
    event_type: 'bought',
    from_location_id: null,
    to_location_id: 'loc-1',
    note: 'Купил 3 штуки на будущее. Магазин "Авто-маг".',
    occurred_at: '2026-04-10',
  },
  {
    id: 'reg-3',
    thing_id: 'thing-5',
    event_type: 'moved',
    from_location_id: 'loc-1',
    to_location_id: 'loc-3-1',
    note: 'Переложил в багажник чтобы не забыть при следующем ТО.',
    occurred_at: '2026-04-12',
  },
  {
    id: 'reg-4',
    thing_id: 'thing-8',
    event_type: 'lent',
    from_location_id: 'loc-1-1',
    to_location_id: null,
    note: 'Дал Шурику на выходные для ремонта балкона.',
    occurred_at: '2026-04-20',
    lent_to: 'Шурик',
    return_expected: '2026-04-28',
  },
  {
    id: 'reg-5',
    thing_id: 'thing-7',
    event_type: 'installed',
    from_location_id: null,
    to_location_id: 'loc-1-1',
    note: 'Установил в 4й слот сервера.',
    occurred_at: '2024-02-16',
  },
];

// ── Статусы ───────────────────────────────────────────────────────
export const THING_STATUSES = {
  active:   { label: 'В использовании', color: 'green' },
  stored:   { label: 'На хранении',     color: 'blue' },
  ordered:  { label: 'Заказан',         color: 'orange' },
  installed:{ label: 'Установлен',      color: 'teal' },
  lent:     { label: 'Одолжен',         color: 'yellow' },
  sold:     { label: 'Продан',          color: 'gray' },
  lost:     { label: 'Утерян',          color: 'red' },
  disposed: { label: 'Утилизирован',    color: 'gray' },
};

// ── Типы событий Register ─────────────────────────────────────────
export const REGISTER_EVENT_TYPES = {
  bought:    { label: 'Куплен',      color: 'green',  icon: 'shopping-cart' },
  ordered:   { label: 'Заказан',     color: 'orange', icon: 'truck-delivery' },
  moved:     { label: 'Перемещён',   color: 'blue',   icon: 'transfer' },
  installed: { label: 'Установлен',  color: 'teal',   icon: 'tool' },
  lent:      { label: 'Одолжен',     color: 'yellow', icon: 'user-share' },
  returned:  { label: 'Возвращён',   color: 'cyan',   icon: 'arrow-back' },
  sold:      { label: 'Продан',      color: 'gray',   icon: 'currency-dollar' },
  lost:      { label: 'Потерян',     color: 'red',    icon: 'alert-triangle' },
  stolen:    { label: 'Украден',     color: 'red',    icon: 'alert-triangle' },
  disposed:  { label: 'Выброшен',    color: 'gray',   icon: 'trash' },
  repaired:  { label: 'Отремонтирован', color: 'violet', icon: 'tool' },
  received:  { label: 'Получен',     color: 'green',  icon: 'package' },
};
